
import { Category, PhraseData } from './types';

export const CATEGORIES: Category[] = [
  { id: 'recents', labelEn: 'Recent', labelHi: 'हाल ही में', icon: '🕒', colorTheme: 'slate-500', soundProfile: 'neutral' },
  { id: 'keyboard', labelEn: 'Type', labelHi: 'टाइप', icon: '⌨️', colorTheme: 'zinc-700', soundProfile: 'neutral' },
  { id: 'sign', labelEn: 'Sign Cam', labelHi: 'साइन कैमरा', icon: '📷', colorTheme: 'rose-500', soundProfile: 'alert' },
  { id: 'needs', labelEn: 'Basic Needs', labelHi: 'ज़रूरतें', icon: '🖐️', colorTheme: 'blue-500', soundProfile: 'question' },
  { id: 'food', labelEn: 'Food & Drink', labelHi: 'खाना पीना', icon: '🍔', colorTheme: 'orange-500', soundProfile: 'happy' },
  { id: 'daily_chat', labelEn: 'Daily Chat', labelHi: 'दैनिक बातचीत', icon: '🗣️', colorTheme: 'teal-500', soundProfile: 'social' },
  { id: 'feelings', labelEn: 'Feelings', labelHi: 'भावनाएं', icon: '😊', colorTheme: 'yellow-500', soundProfile: 'happy' },
  { id: 'places', labelEn: 'Places', labelHi: 'जगहें', icon: '🏠', colorTheme: 'green-500', soundProfile: 'neutral' },
  { id: 'emergency', labelEn: 'Emergency', labelHi: 'आपातकालीन', icon: '🚨', colorTheme: 'red-600', soundProfile: 'alert' },
  { id: 'social', labelEn: 'Social', labelHi: 'बातचीत', icon: '💬', colorTheme: 'purple-500', soundProfile: 'social' },
];

export const PHRASES: Record<string, PhraseData[]> = {
  needs: [
    { id: 'toilet', label: 'Toilet', phraseEn: 'I want to go to the toilet', phraseHi: 'मुझे शौचालय जाना है', emoji: '🚽', bgColor: 'bg-blue-100', soundProfile: 'alert' },
    { id: 'sleep', label: 'Sleep', phraseEn: 'I want to sleep', phraseHi: 'मुझे सोना है', emoji: '🛏️', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'medicine', label: 'Medicine', phraseEn: 'I need my medicine', phraseHi: 'मुझे अपनी दवाई चाहिए', emoji: '💊', bgColor: 'bg-red-50', soundProfile: 'alert' },
    { id: 'water_needs', label: 'Water', phraseEn: 'I need water', phraseHi: 'मुझे पानी चाहिए', emoji: '💧', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'bath', label: 'Bath', phraseEn: 'I want a bath', phraseHi: 'मुझे नहाना है', emoji: '🛁', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'dress', label: 'Clothes', phraseEn: 'Change my clothes', phraseHi: 'कपड़े बदल दो', emoji: '👕', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'wash', label: 'Wash Hands', phraseEn: 'I want to wash my hands', phraseHi: 'मुझे हाथ धोने हैं', emoji: '🧼', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'brush', label: 'Brush', phraseEn: 'I want to brush my teeth', phraseHi: 'मुझे ब्रश करना है', emoji: '🪥', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'pain', label: 'Pain', phraseEn: 'I am in pain', phraseHi: 'मुझे दर्द हो रहा है', emoji: '🤕', bgColor: 'bg-red-100', soundProfile: 'sad' },
    { id: 'glasses', label: 'Glasses', phraseEn: 'Where are my glasses?', phraseHi: 'मेरा चश्मा कहाँ है?', emoji: '👓', bgColor: 'bg-blue-100', soundProfile: 'question' },
    { id: 'phone', label: 'Phone', phraseEn: 'Where is my phone?', phraseHi: 'मेरा फोन कहाँ है?', emoji: '📱', bgColor: 'bg-blue-100', soundProfile: 'question' },
    { id: 'cold', label: 'Cold', phraseEn: 'I am feeling cold', phraseHi: 'मुझे ठंड लग रही है', emoji: '🥶', bgColor: 'bg-blue-100', soundProfile: 'sad' },
    { id: 'hot_feel', label: 'Hot', phraseEn: 'I am feeling hot', phraseHi: 'मुझे गर्मी लग रही है', emoji: '🥵', bgColor: 'bg-blue-100', soundProfile: 'sad' },
    { id: 'towel', label: 'Towel', phraseEn: 'I need a towel', phraseHi: 'मुझे तौलिया चाहिए', emoji: '🧖', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'blanket', label: 'Blanket', phraseEn: 'I need a blanket', phraseHi: 'मुझे कंबल चाहिए', emoji: '🛌', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'pillow', label: 'Pillow', phraseEn: 'I need a pillow', phraseHi: 'मुझे तकिया चाहिए', emoji: '🛏️', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'tissue', label: 'Tissue', phraseEn: 'I need a tissue', phraseHi: 'मुझे टिश्यू चाहिए', emoji: '🤧', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'comb', label: 'Comb', phraseEn: 'I want to comb my hair', phraseHi: 'मुझे बाल बनाने हैं', emoji: '💇', bgColor: 'bg-blue-100', soundProfile: 'neutral' },
    { id: 'quiet', label: 'Quiet', phraseEn: 'It is too loud', phraseHi: 'बहुत शोर है', emoji: '🤫', bgColor: 'bg-blue-100', soundProfile: 'alert' },
    { id: 'lights_on', label: 'Light On', phraseEn: 'Turn the light on', phraseHi: 'लाइट जलाओ', emoji: '💡', bgColor: 'bg-yellow-50', soundProfile: 'happy' },
    { id: 'lights_off', label: 'Light Off', phraseEn: 'Turn the light off', phraseHi: 'लाइट बंद करो', emoji: '🌑', bgColor: 'bg-slate-200', soundProfile: 'neutral' },
    { id: 'charger', label: 'Charger', phraseEn: 'I need a charger', phraseHi: 'मुझे चार्जर चाहिए', emoji: '🔌', bgColor: 'bg-orange-100', soundProfile: 'alert' },
  ],
  food: [
    { id: 'water', label: 'Water', phraseEn: 'I need water', phraseHi: 'मुझे पानी चाहिए', emoji: '💧', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'food', label: 'Food', phraseEn: 'I want food', phraseHi: 'मुझे खाना चाहिए', emoji: '🥘', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'juice', label: 'Juice', phraseEn: 'I want juice', phraseHi: 'मुझे जूस चाहिए', emoji: '🧃', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'tea', label: 'Tea', phraseEn: 'I want tea', phraseHi: 'मुझे चाय चाहिए', emoji: '☕', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'milk', label: 'Milk', phraseEn: 'I want milk', phraseHi: 'मुझे दूध चाहिए', emoji: '🥛', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'fruit', label: 'Fruit', phraseEn: 'I want fruit', phraseHi: 'मुझे फल चाहिए', emoji: '🍎', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'rice', label: 'Rice', phraseEn: 'I want rice', phraseHi: 'मुझे चावल चाहिए', emoji: '🍚', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'bread', label: 'Bread', phraseEn: 'I want bread', phraseHi: 'मुझे ब्रेड चाहिए', emoji: '🍞', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'snack', label: 'Snack', phraseEn: 'I want a snack', phraseHi: 'मुझे नाश्ता चाहिए', emoji: '🍪', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'sweet', label: 'Sweet', phraseEn: 'I want something sweet', phraseHi: 'मुझे कुछ मीठा चाहिए', emoji: '🍬', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'spoon', label: 'Spoon', phraseEn: 'I need a spoon', phraseHi: 'मुझे चम्मच चाहिए', emoji: '🥄', bgColor: 'bg-orange-100', soundProfile: 'neutral' },
    { id: 'plate', label: 'Plate', phraseEn: 'I need a plate', phraseHi: 'मुझे थाली चाहिए', emoji: '🍽️', bgColor: 'bg-orange-100', soundProfile: 'neutral' },
    { id: 'chicken', label: 'Chicken', phraseEn: 'I want chicken', phraseHi: 'मुझे चिकन चाहिए', emoji: '🍗', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'egg', label: 'Egg', phraseEn: 'I want eggs', phraseHi: 'मुझे अंडे चाहिए', emoji: '🥚', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'veg', label: 'Vegetables', phraseEn: 'I want vegetables', phraseHi: 'मुझे सब्जियां चाहिए', emoji: '🥦', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'pizza', label: 'Pizza', phraseEn: 'I want pizza', phraseHi: 'मुझे पिज्जा चाहिए', emoji: '🍕', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'burger', label: 'Burger', phraseEn: 'I want a burger', phraseHi: 'मुझे बर्गर चाहिए', emoji: '🍔', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'soup', label: 'Soup', phraseEn: 'I want s सूप', phraseHi: 'मुझे सूप चाहिए', emoji: '🥣', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'icecream', label: 'Ice Cream', phraseEn: 'I want ice cream', phraseHi: 'मुझे आइसक्रीम चाहिए', emoji: '🍦', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'chocolate', label: 'Chocolate', phraseEn: 'I want chocolate', phraseHi: 'मुझे चॉकलेट चाहिए', emoji: '🍫', bgColor: 'bg-orange-100', soundProfile: 'happy' },
    { id: 'sandwich', label: 'Sandwich', phraseEn: 'I want a sandwich', phraseHi: 'मुझे सैंडविच चाहिए', emoji: '🥪', bgColor: 'bg-orange-100', soundProfile: 'happy' },
  ],
  daily_chat: [
    { id: 'please', label: 'Please', phraseEn: 'Please', phraseHi: 'कृपया', emoji: '🙏', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'sorry', label: 'Sorry', phraseEn: 'I am sorry', phraseHi: 'मुझे माफ़ कर दो', emoji: '😔', bgColor: 'bg-teal-100', soundProfile: 'sad' },
    { id: 'how_are_you', label: 'How are you?', phraseEn: 'How are you?', phraseHi: 'आप कैसे हैं?', emoji: '❓', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'im_good', label: 'I am good', phraseEn: 'I am good', phraseHi: 'मैं ठीक हूँ', emoji: '👍', bgColor: 'bg-teal-100', soundProfile: 'happy' },
    { id: 'what_name', label: 'Your Name?', phraseEn: 'What is your name?', phraseHi: 'आपका नाम क्या है?', emoji: '📛', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'my_name', label: 'My Name', phraseEn: 'My name is...', phraseHi: 'मेरा नाम... है', emoji: '😊', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'what_doing', label: 'What doing?', phraseEn: 'What are you doing?', phraseHi: 'आप क्या कर रहे हैं?', emoji: '🤷', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'good_morning', label: 'Morning', phraseEn: 'Good Morning', phraseHi: 'सुप्रभात', emoji: '🌅', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'good_night', label: 'Night', phraseEn: 'Good Night', phraseHi: 'शुभ रात्रि', emoji: '🌙', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'time', label: 'Time?', phraseEn: 'What time is it?', phraseHi: 'समय क्या हुआ है?', emoji: '⌚', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'good_job', label: 'Good Job', phraseEn: 'Good Job', phraseHi: 'बहुत अच्छे', emoji: '👏', bgColor: 'bg-teal-100', soundProfile: 'happy' },
    { id: 'look', label: 'Look', phraseEn: 'Look at this', phraseHi: 'इसे देखो', emoji: '👀', bgColor: 'bg-teal-100', soundProfile: 'alert' },
    { id: 'dont_know', label: 'Don\'t Know', phraseEn: 'I do not know', phraseHi: 'मुझे नहीं पता', emoji: '😶', bgColor: 'bg-teal-100', soundProfile: 'sad' },
    { id: 'stop', label: 'Stop', phraseEn: 'Stop it please', phraseHi: 'कृपया रुकें', emoji: '🛑', bgColor: 'bg-red-50', soundProfile: 'alert' },
    { id: 'more', label: 'More', phraseEn: 'I want more', phraseHi: 'मुझे और चाहिए', emoji: '➕', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'finished', label: 'Finished', phraseEn: 'I am finished', phraseHi: 'मेरा हो गया', emoji: '✅', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'wait', label: 'Wait', phraseEn: 'Please wait a moment', phraseHi: 'कृपया एक पल रुकें', emoji: '✋', bgColor: 'bg-teal-100', soundProfile: 'alert' },
    { id: 'come_here', label: 'Come Here', phraseEn: 'Please come here', phraseHi: 'कृपया यहाँ आएं', emoji: '👇', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'lets_go', label: 'Let\'s Go', phraseEn: 'Let us go now', phraseHi: 'चलो अब चलते हैं', emoji: '🚶', bgColor: 'bg-teal-100', soundProfile: 'happy' },
    { id: 'good_afternoon', label: 'Afternoon', phraseEn: 'Good Afternoon', phraseHi: 'शुभ दोपहर', emoji: '☀️', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'good_evening', label: 'Evening', phraseEn: 'Good Evening', phraseHi: 'शुभ संध्या', emoji: '🌇', bgColor: 'bg-teal-100', soundProfile: 'social' },
    { id: 'like', label: 'I Like', phraseEn: 'I like this', phraseHi: 'मुझे यह पसंद है', emoji: '😍', bgColor: 'bg-teal-100', soundProfile: 'happy' },
    { id: 'dont_like', label: 'No Like', phraseEn: 'I do not like this', phraseHi: 'मुझे यह पसंद नहीं है', emoji: '🤢', bgColor: 'bg-teal-100', soundProfile: 'sad' },
    { id: 'want', label: 'I Want', phraseEn: 'I want this', phraseHi: 'मुझे यह चाहिए', emoji: '🤲', bgColor: 'bg-teal-100', soundProfile: 'question' },
    { id: 'dont_want', label: 'No Want', phraseEn: 'I do not want this', phraseHi: 'मुझे यह नहीं चाहिए', emoji: '🙅', bgColor: 'bg-teal-100', soundProfile: 'sad' },
    { id: 'later', label: 'Later', phraseEn: 'I will do it later', phraseHi: 'मैं बाद में करूँगा', emoji: '⏲️', bgColor: 'bg-orange-100', soundProfile: 'neutral' },
  ],
  feelings: [
    { id: 'happy', label: 'Happy', phraseEn: 'I am happy', phraseHi: 'मैं खुश हूँ', emoji: '😃', bgColor: 'bg-yellow-100', soundProfile: 'happy' },
    { id: 'sad', label: 'Sad', phraseEn: 'I am feeling sad', phraseHi: 'मैं दुखी हूँ', emoji: '😟', bgColor: 'bg-yellow-100', soundProfile: 'sad' },
    { id: 'angry', label: 'Angry', phraseEn: 'I am angry', phraseHi: 'मुझे गुस्सा आ रहा है', emoji: '😠', bgColor: 'bg-red-100', soundProfile: 'alert' },
    { id: 'tired', label: 'Tired', phraseEn: 'I am tired', phraseHi: 'मैं थक गया हूँ', phraseHiFemale: 'मैं थक गई हूँ', emoji: '😫', bgColor: 'bg-yellow-100', soundProfile: 'sad' },
    { id: 'bored', label: 'Bored', phraseEn: 'I am bored', phraseHi: 'मैं बोर हो रहा हूँ', phraseHiFemale: 'मैं बोर हो रही हूँ', emoji: '😐', bgColor: 'bg-yellow-100', soundProfile: 'sad' },
    { id: 'excited', label: 'Excited', phraseEn: 'I am excited', phraseHi: 'मैं बहुत उत्साहित हूँ', emoji: '🤩', bgColor: 'bg-yellow-100', soundProfile: 'happy' },
    { id: 'scared', label: 'Scared', phraseEn: 'I am scared', phraseHi: 'मुझे डर लग रहा है', emoji: '😨', bgColor: 'bg-purple-100', soundProfile: 'alert' },
    { id: 'confused', label: 'Confused', phraseEn: 'I am confused', phraseHi: 'मैं उलझन में हूँ', emoji: '😕', bgColor: 'bg-yellow-100', soundProfile: 'question' },
    { id: 'sick', label: 'Sick', phraseEn: 'I feel sick', phraseHi: 'मेरी तबीयत ठीक नहीं है', emoji: '🤢', bgColor: 'bg-green-100', soundProfile: 'sad' },
    { id: 'lonely', label: 'Lonely', phraseEn: 'I feel lonely', phraseHi: 'मुझे अकेलापन लग रहा है', emoji: '🙍', bgColor: 'bg-yellow-100', soundProfile: 'sad' },
    { id: 'shy', label: 'Shy', phraseEn: 'I feel shy', phraseHi: 'मुझे शर्म आ रही है', emoji: '🙈', bgColor: 'bg-yellow-100', soundProfile: 'neutral' },
    { id: 'nervous', label: 'Nervous', phraseEn: 'I am nervous', phraseHi: 'मैं घबराया हुआ हूँ', phraseHiFemale: 'मैं घबराई हुई हूँ', emoji: '😬', bgColor: 'bg-yellow-100', soundProfile: 'alert' },
    { id: 'surprised', label: 'Surprised', phraseEn: 'I am surprised', phraseHi: 'मैं हैरान हूँ', emoji: '😲', bgColor: 'bg-yellow-100', soundProfile: 'happy' },
    { id: 'proud', label: 'Proud', phraseEn: 'I am proud', phraseHi: 'मुझे गर्व है', emoji: '😎', bgColor: 'bg-yellow-100', soundProfile: 'happy' },
    { id: 'thirsty', label: 'Thirsty', phraseEn: 'I am thirsty', phraseHi: 'मुझे प्यास लगी है', emoji: '🥤', bgColor: 'bg-orange-100', soundProfile: 'alert' },
    { id: 'hungry', label: 'Hungry', phraseEn: 'I am hungry', phraseHi: 'मुझे भूख लगी है', emoji: '🍽️', bgColor: 'bg-orange-100', soundProfile: 'alert' },
    { id: 'relaxed', label: 'Relaxed', phraseEn: 'I feel relaxed', phraseHi: 'मैं आराम महसूस कर रहा हूँ', phraseHiFemale: 'मैं आराम महसूस रही हूँ', emoji: '😌', bgColor: 'bg-orange-100', soundProfile: 'happy' },
  ],
  places: [
    { id: 'home', label: 'Home', phraseEn: 'I want to go home', phraseHi: 'मुझे घर जाना है', emoji: '🏡', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'park', label: 'Park', phraseEn: 'Let us go to the park', phraseHi: 'चलो पार्क चलते हैं', emoji: '🌳', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'school', label: 'School', phraseEn: 'Take me to school', phraseHi: 'मुझे स्कूल ले चलो', emoji: '🏫', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'shop', label: 'Shop', phraseEn: 'Let us go to the shop', phraseHi: 'चलो दुकान चलते हैं', emoji: '🏪', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'kitchen', label: 'Kitchen', phraseEn: 'I want to go to the kitchen', phraseHi: 'मुझे रसोई में जाना है', emoji: '🍳', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'garden', label: 'Garden', phraseEn: 'I want to go to the garden', phraseHi: 'मुझे बगीचे में जाना है', emoji: '🌻', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'car', label: 'Car', phraseEn: 'I want to go in the car', phraseHi: 'मुझे गाड़ी में जाना है', emoji: '🚗', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'bus', label: 'Bus', phraseEn: 'I want to take the bus', phraseHi: 'मुझे बस लेनी है', emoji: '🚌', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'outside', label: 'Outside', phraseEn: 'I want to go outside', phraseHi: 'मुझे बाहर जाना है', emoji: '🚪', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'work', label: 'Work', phraseEn: 'I want to go to work', phraseHi: 'मुझे काम पर जाना है', emoji: '💼', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'bathroom', label: 'Bathroom', phraseEn: 'I want to go to the bathroom', phraseHi: 'मुझे बाथरूम जाना है', emoji: '🚽', bgColor: 'bg-green-100', soundProfile: 'alert' },
    { id: 'bedroom', label: 'Bedroom', phraseEn: 'I want to go to the bedroom', phraseHi: 'मुझे शयनकक्ष में जाना है', emoji: '🛏️', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'cinema', label: 'Movies', phraseEn: 'I want to go to the movies', phraseHi: 'मुझे सिनेमा जाना है', emoji: '🎬', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'market', label: 'Market', phraseEn: 'I want to go to the market', phraseHi: 'मुझे बाज़ार जाना है', emoji: '🏬', bgColor: 'bg-green-100', soundProfile: 'neutral' },
    { id: 'restaurant', label: 'Restaurant', phraseEn: 'I want to go to a restaurant', phraseHi: 'मुझे रेस्टोरेंट जाना है', emoji: '🍽️', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'library', label: 'Library', phraseEn: 'I want to go to the library', phraseHi: 'मुझे पुस्तकालय जाना है', emoji: '📚', bgColor: 'bg-orange-100', soundProfile: 'neutral' },
  ],
  emergency: [
    { id: 'help', label: 'Help', phraseEn: 'Please help me', phraseHi: 'कृपया मेरी मदद करें', emoji: '🆘', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'doctor', label: 'Doctor', phraseEn: 'I need a doctor', phraseHi: 'मुझे डॉक्टर की ज़रूरत है', emoji: '👨‍⚕️', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'hospital', label: 'Hospital', phraseEn: 'Take me to the hospital', phraseHi: 'मुझे अस्पताल ले चलो', emoji: '🏥', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'call', label: 'Call', phraseEn: 'Please call my family', phraseHi: 'कृपया मेरे परिवार को फोन करें', emoji: '📞', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'police', label: 'Police', phraseEn: 'Call the police', phraseHi: 'पुलिस को बुलाओ', emoji: '🚓', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'lost', label: 'Lost', phraseEn: 'I am lost', phraseHi: 'मैं खो गया हूँ', phraseHiFemale: 'मैं खो गई हूँ', emoji: '🧭', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'fall', label: 'Fell Down', phraseEn: 'I fell down', phraseHi: 'मैं गिर गया', phraseHiFemale: 'मैं गिर गई', emoji: '🤕', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'cant_breathe', label: 'Breath', phraseEn: 'I cannot breathe', phraseHi: 'मैं सांस नहीं ले पा रहा', phraseHiFemale: 'मैं सांस नहीं ले पा रही', emoji: '🫁', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'allergy', label: 'Allergy', phraseEn: 'I have an allergy', phraseHi: 'मुझे एलर्जी है', emoji: '🤧', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'fire', label: 'Fire', phraseEn: 'There is a fire', phraseHi: 'आग लगी है', emoji: '🔥', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'stomach_ache', label: 'Stomach', phraseEn: 'My stomach hurts', phraseHi: 'मेरे पेट में दर्द है', emoji: '😫', bgColor: 'bg-red-200', soundProfile: 'sad' },
    { id: 'headache', label: 'Headache', phraseEn: 'My head hurts', phraseHi: 'मेरे सिर में दर्द है', emoji: '🤯', bgColor: 'bg-red-200', soundProfile: 'sad' },
    { id: 'danger', label: 'Danger', phraseEn: 'I am in danger', phraseHi: 'मैं खतरे में हूँ', emoji: '⚠️', bgColor: 'bg-red-200', soundProfile: 'alert' },
    { id: 'ambulance', label: 'Ambulance', phraseEn: 'Call an ambulance', phraseHi: 'एम्बुलेंस को बुलाओ', emoji: '🚑', bgColor: 'bg-orange-100', soundProfile: 'alert' },
  ],
  social: [
    { id: 'hello', label: 'Hello', phraseEn: 'Hello', phraseHi: 'नमस्ते', emoji: '👋', bgColor: 'bg-purple-100', soundProfile: 'social' },
    { id: 'bye', label: 'Bye', phraseEn: 'Goodbye', phraseHi: 'अलविदा', emoji: '🙋', bgColor: 'bg-purple-100', soundProfile: 'social' },
    { id: 'yes', label: 'Yes', phraseEn: 'Yes', phraseHi: 'हाँ', emoji: '👍', bgColor: 'bg-green-100', soundProfile: 'happy' },
    { id: 'no', label: 'No', phraseEn: 'No', phraseHi: 'नहीं', emoji: '👎', bgColor: 'bg-red-100', soundProfile: 'sad' },
    { id: 'maybe', label: 'Maybe', phraseEn: 'Maybe', phraseHi: 'शायद', emoji: '🤷', bgColor: 'bg-yellow-100', soundProfile: 'question' },
    { id: 'thanks', label: 'Thanks', phraseEn: 'Thank you', phraseHi: 'धन्यवाद', emoji: '🙏', bgColor: 'bg-purple-100', soundProfile: 'social' },
    { id: 'love', label: 'Love', phraseEn: 'I love you', phraseHi: 'मैं तुमसे प्यार करता हूँ', phraseHiFemale: 'मैं तुमसे प्यार करती हूँ', emoji: '❤️', bgColor: 'bg-pink-100', soundProfile: 'happy' },
    { id: 'who', label: 'Who?', phraseEn: 'Who is that?', phraseHi: 'वह कौन है?', emoji: '👤', bgColor: 'bg-purple-100', soundProfile: 'question' },
    { id: 'when', label: 'When?', phraseEn: 'When?', phraseHi: 'कब?', emoji: '🕒', bgColor: 'bg-purple-100', soundProfile: 'question' },
    { id: 'why', label: 'Why?', phraseEn: 'Why?', phraseHi: 'क्यों?', emoji: '❓', bgColor: 'bg-purple-100', soundProfile: 'question' },
    { id: 'congrats', label: 'Congrats', phraseEn: 'Congratulations', phraseHi: 'बधाई हो', emoji: '🎉', bgColor: 'bg-purple-100', soundProfile: 'happy' },
    { id: 'nice', label: 'Nice', phraseEn: 'That is nice', phraseHi: 'यह अच्छा है', emoji: '✨', bgColor: 'bg-purple-100', soundProfile: 'happy' },
    { id: 'birthday', label: 'Birthday', phraseEn: 'Happy Birthday', phraseHi: 'जन्मदिन मुबारक हो', emoji: '🎂', bgColor: 'bg-purple-100', soundProfile: 'happy' },
    { id: 'friend', label: 'Friend', phraseEn: 'My friend', phraseHi: 'मेरा दोस्त', emoji: '🤝', bgColor: 'bg-purple-100', soundProfile: 'social' },
    { id: 'family', label: 'Family', phraseEn: 'My family', phraseHi: 'मेरा परिवार', emoji: '👨‍👩‍👧‍👦', bgColor: 'bg-purple-100', soundProfile: 'social' },
    { id: 'joke', label: 'Joke', phraseEn: 'Tell me a joke', phraseHi: 'मुझे एक चुटकुला सुनाओ', emoji: '😆', bgColor: 'bg-purple-100', soundProfile: 'happy' },
    { id: 'good_luck', label: 'Good Luck', phraseEn: 'Good luck', phraseHi: 'शुभकामनाएँ', emoji: '🤞', bgColor: 'bg-orange-100', soundProfile: 'happy' },
  ]
};
